services:
  app:
    build:
      context: .
    ports:
      - "3300:3300"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      - ENV=local
    command: sh -c "go mod tidy && go run cmd/goat-cg/main.go"