version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "3300:3300"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    command: sh -c "go mod tidy && go mod download && go build cmd/goat-cg/main.go && ./main"
    restart: always
